using System;
using System.Security.Cryptography.X509Certificates;

class Program
{
    static void Main(string[] args)
    {
        string response = "yes";
        Console.WriteLine("   In the Guess the Magic Number game the computer picks a magic number, and then the user tries to guess it. After each guess, the computer tells the user to guess 'higher' or 'lower' until they guess the magic number.");
        
        while (response == "yes")
        {
            int guesses = 1;
            Random randomGenerator = new Random();
            int number = randomGenerator.Next(1, 100);
            Console.WriteLine($"The Magic Number is {number}");

            Console.WriteLine("What is your guess? ");
            string guess = Console.ReadLine();
            int x = int.Parse(guess);

            //x refers to the user's guess and number is the value generated by random
            while (x != number)
            {
                if (x > number)
                {
                    Console.WriteLine("Lower ");
                    guesses = guesses + 1;
                }
                else if (x < number)
                {
                    Console.WriteLine("Higher ");
                    guesses = guesses + 1;
                }

                Console.WriteLine("What is your guess? ");
                guess = Console.ReadLine();
                x = int.Parse(guess);
            }
            if (guesses > 1)
            {
                Console.WriteLine($"Congratulations! You guessed the Magic Number in {guesses} guesses!");
            }
            else
            {
                Console.WriteLine($"Congratulations! You guessed the Magic Number in {guesses} guess!");
            }
            
            Console.WriteLine("Do you Want to play again? (Response must be 'yes' to play again.) ");
            response = Console.ReadLine();
        }
    }
}